[package]
name = "rustls-wolfcrypt-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.23.9"
chacha20poly1305 = { version = "0.10", default-features = false, features = ["alloc"] }
der = "0.7"
ecdsa = "0.16.8"
hmac = "0.12"
hpke-rs = "0.2"
hpke-rs-crypto = "0.2"
hpke-rs-rust-crypto = "0.2"
p256 = { version = "0.13.2", default-features = false, features = ["alloc", "ecdsa", "pkcs8"] }
pkcs8 = "0.10.2"
rand_core = { version = "0.6", features = ["getrandom"] }
rsa = { version = "0.9", features = ["sha2"], default-features = false }
sha2 = { version = "0.10", default-features = false }
signature = "2"
webpki = { package = "rustls-webpki", version = "0.102", features = ["alloc"], default-features = false }
x25519-dalek = "2"
wolfssl = "1.0.0"
wolfcrypt-rs = { path = "../wolfcrypt-rs" }
hex-literal = "0.4.1"
hex = "0.4.3"
foreign-types = "0.5.0"
rustls-pki-types = "1.7.0"

[dev-dependencies]
env_logger = "0.10" # 0.11 requires 1.71 MSRV even as a dev-dep (due to manifest features)
rcgen = "0.11.3"
webpki-roots = "0.26"

[features]
default = ["std"]
std = ["hpke-rs/std", "hpke-rs-crypto/std", "pkcs8/std", "rustls/std"]
