[package]
name = "rustls-wolfcrypt-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.23.14"
chacha20poly1305 = { version = "0.10", default-features = false, features = ["alloc"] }
der = "0.7"
ecdsa = "0.16.9"
hmac = "0.12"
hpke-rs = "0.2"
hpke-rs-crypto = "0.2"
hpke-rs-rust-crypto = "0.2"
p256 = { version = "0.13.2", default-features = false, features = ["alloc", "ecdsa", "pkcs8"] }
pkcs8 = "0.10.2"
rand_core = { version = "0.6", features = ["getrandom"] }
rsa = { version = "0.9", features = ["sha2"], default-features = false }
sha2 = { version = "0.10", default-features = false }
signature = "2"
webpki = { package = "rustls-webpki", version = "0.102", features = ["alloc"], default-features = false }
x25519-dalek = "2"
wolfssl = "1.1.0"
wolfcrypt-rs = { path = "../wolfcrypt-rs" }
hex-literal = "0.4.1"
hex = "0.4.3"
foreign-types = "0.5.0"
rustls-pki-types = "1.8.0"
tokio-rustls = { version = "0.26", default-features = false  }
log = "0.4.22"
env_logger = "0.11.5"
hyper = "1.4.1"
hyper-util = "0.1.8"
aes-gcm = "0.10.3"
rustls-pemfile = "2.1.3"

[dev-dependencies]
rcgen = "0.13"
serial_test = "3.1.1"
tokio = { version = "1.40", features = ["macros", "rt", "net", "io-util", "io-std"] }
webpki-roots = "0.26"

[features]
default = ["std"]
std = ["hpke-rs/std", "hpke-rs-crypto/std", "pkcs8/std", "rustls/std"]
