[package]
name = "wolfcrypt-rs"
version = "0.1.0"
edition = "2021"

[features]
std = []

[build-dependencies]
bindgen = "0.70.1"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
